server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/drivers/**

        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/teams/**

        - id: race-service
          uri: lb://race-service
          predicates:
            - Path=/races/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
