server:
  port: 8082

spring:
  application:
    name: team-service

  datasource:
    url: jdbc:postgresql://postgres:5432/f1db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
